# Alokasi memori JVM Gradle daemon dibatasi pada 1024MB agar aman untuk RAM 3.7GB host (Anti-Freeze)
org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=384m -XX:+UseG1GC -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.caching=true
org.gradle.vfs.watch=false

# Lokasi JDK 17
org.gradle.java.home=/home/drgxel/.local/share/jdk17

# Pengaturan modern AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin Daemon RAM limit
kotlin.daemon.jvmargs=-Xmx512m
